name       : fsearch
version    : 0.1.3
release    : 3
source     :
    - https://github.com/cboxdoerfer/fsearch/archive/refs/tags/0.1.3.tar.gz : b29ca3f49f2847f280320e0b346a5e6ec98e76e3523c78dbd8178a8f8f19b5dc
license    : GPL-2.0-or-later
component  : system.utils
summary    : A fast file search utility for Unix-like systems based on GTK+3
description: |
    FSearch is a fast file search utility, inspired by Everything Search Engine. It's written in C and based on GTK3.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre)
    - pkgconfig(icu-uc)
    - autoconf-archive
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
