name       : fsearch
version    : 0.2.1
release    : 6
source     :
    - https://github.com/cboxdoerfer/fsearch/archive/refs/tags/0.2.1.tar.gz : 5fb8f8280ea4417d949b055bbd576161a42d360727abea3d7e9c9300c978a650
license    : GPL-2.0-or-later
component  : system.utils
summary    : A fast file search utility for Unix-like systems based on GTK+3
description: |
    FSearch is a fast file search utility, inspired by Everything Search Engine. It's written in C and based on GTK3.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - pkgconfig(icu-uc)
    - autoconf-archive
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
