name       : fsearch
version    : '0.2'
release    : 5
source     :
    - https://github.com/cboxdoerfer/fsearch/archive/refs/tags/0.2.tar.gz : 96d1eac47fec8eb4e76a4fb8dfbc0b45365569a62c6f0e91d69b8a5e2ca1eaea
license    : GPL-2.0-or-later
component  : system.utils
summary    : A fast file search utility for Unix-like systems based on GTK+3
description: |
    FSearch is a fast file search utility, inspired by Everything Search Engine. It's written in C and based on GTK3.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - pkgconfig(icu-uc)
    - autoconf-archive
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
